
# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: forecast

on:
  schedule:
    - cron: '0 8 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    # Skip CI if [ci skip] in the commit message
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # cpu version of pytorch
        pip install -r requirements.txt

    - name: Phenology
      run: |
        python phenology.py
